//
//  ProgressBarDraw.swift
//  ProgressBar Demo
//
//  Created by Szabolcs Toth on 10/26/18.
//  Copyright © 2018 . All rights reserved.
//
//  Generated by PaintCode
//  http://www.paintcodeapp.com
//



import Cocoa

public class ProgressBarDraw : NSObject {

    //// Drawing Methods

    @objc dynamic public class func drawProgressBar(frame: NSRect = NSRect(x: 0, y: 0, width: 300, height: 16), progress: CGFloat = 95) {
        //// General Declarations
        // This non-generic function dramatically improves compilation times of complex expressions.
        func fastFloor(_ x: CGFloat) -> CGFloat { return floor(x) }

        //// Color Declarations
        let color = NSColor(red: 0.541, green: 0.612, blue: 0.855, alpha: 1)

        //// Progress Border Drawing
        let progressBorderPath = NSBezierPath(roundedRect: NSRect(x: frame.minX + 1, y: frame.minY + frame.height - 15, width: fastFloor((frame.width - 1) * 0.99666 + 0.5), height: 14), xRadius: 7, yRadius: 7)
        color.setStroke()
        progressBorderPath.lineWidth = 1
        progressBorderPath.stroke()


        //// Progress Active Drawing
        let progressActivePath = NSBezierPath(roundedRect: NSRect(x: 2, y: 2, width: progress, height: 12), xRadius: 6, yRadius: 6)
        color.setFill()
        progressActivePath.fill()
    }

}
